Fix compiling for wasm32-unknown-emscripten target
 error[E0428]: the name `inner` is defined multiple times
  --> /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/sys.rs:25:1
   |
21 | mod inner;
   | ---------- previous definition of the module `inner` here
...
25 | mod inner;
   | ^^^^^^^^^^ `inner` redefined here
   |
   = note: `inner` must be defined only once in the type namespace of this module